### PR TITLE
Remove duplicated port from k8s authenticator configmap

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/giantswarm/issues/21841

## Checklist

- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by anvddriesch** [comment]
tested on `gauss`

**Review by marians — APPROVED** [review]

**Comment by marians** [comment]
Should we document somewhere that `values.services.kubernetes.api.address` can contain a port number (if it's not 443)?

**Comment by anvddriesch** [comment]
It is in fact 443. I can add a comment in the values file. Or do you know something better?

**Comment by marians** [comment]
> Or do you know something better?

No better idea. The values file is a good place I think.

**Pull request merged**
