### PR TITLE
Update dex to v2.37.0

### PR DESCRIPTION
**Pull request by mogottsch**
## Checklist

- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by anvddriesch — COMMENTED** [review]
I think we also need to bump the version in the chart.yaml so it indicates the right upstream version :)

**Comment by mogottsch** [comment]
@anvddriesch Do you mean `.appVersion` in `Chart.yaml`? It is empty atm, so I thought it was not needed anymore.

**Comment by mogottsch** [comment]
Ah nvm, you mean just the `.version`.

**Review by anvddriesch — APPROVED** [review]
You are right. Somehow I thought we need to manually indicate the upstream version somewhere, but there seems to be no such thing.

**Pull request merged**
