### PR TITLE
Add checksum annotation for automatic restarts on config changes

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/giantswarm/issues/21207

## Checklist

- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by marians** [comment]
Seeing this error: `[ERROR] templates/: template: dex-app/templates/dex/deployment.yaml:8:42: executing "dex-app/templates/dex/deployment.yaml" at <include (print .Template.BasePath "/secret.yaml") .>: error calling include: template: no template "dex-app/templates/secret.yaml" associated with template "gotpl"`

**Review by PrashantR31 — APPROVED** [review]
Nice one. This is a very cool trick.

**Review by anvddriesch — APPROVED** [review]

**Comment by marians** [comment]
@rossf7 Am I doing this right?

**Review by rossf7 — APPROVED** [review]
LGTM

@marians Yes [.Template.BasePath](https://helm.sh/docs/chart_template_guide/builtin_objects/) returns `/dex-app/templates/` so you need `/dex/` in the path.

**Pull request merged**
