### PR TITLE
Align files

### PR DESCRIPTION
**Pull request by architectbot**
This PR is generated by https://github.com/giantswarm/github, it will be merged automatically once all requirements are met

### CODE REVIEW

**Review by marians — CHANGES_REQUESTED** [review]
ABS is failing here

**Comment by marians** [comment]
Slightly strange linter problems:

```nohighlight
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: KubeLinter 0.2.5
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/deployment.yaml: (object: <no namespace>/dex apps/v1, Kind=Deployment) object has 2 replicas but minimum required replicas is 3 (check: minimum-three-replicas, remediation: Increase be number of replicas in the deployment to at least three to increase the fault tolerancy of the deployment.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/deployment.yaml: (object: <no namespace>/dex apps/v1, Kind=Deployment) object in default namespace (check: use-namespace, remediation: Create namespaces for objects in your deployment.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/clusterrolebinding.yaml: (object: <no namespace>/dex rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding) binding to "dex" clusterrole that has [*] access to [*] (check: access-to-create-pods, remediation: Where possible, remove create access to pod objects in the cluster.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/clusterrolebinding.yaml: (object: <no namespace>/dex rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding) binding to "dex" clusterrole that has [*] access to [*] (check: access-to-secrets, remediation: Where possible, remove get, list and watch access to secret objects in the cluster.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/clusterrole.yaml: (object: <no namespace>/dex rbac.authorization.k8s.io/v1, Kind=ClusterRole) wildcard "*" in resource specification (check: wildcard-in-rules, remediation: Where possible replace any use of wildcards in clusterroles and roles with specific objects or actions.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/clusterrole.yaml: (object: <no namespace>/dex rbac.authorization.k8s.io/v1, Kind=ClusterRole) wildcard "*" in verb specification (check: wildcard-in-rules, remediation: Where possible replace any use of wildcards in clusterroles and roles with specific objects or actions.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: helm/dex-app/templates/dex/service.yaml: (object: <no namespace>/dex /v1, Kind=Service) object in default namespace (check: use-namespace, remediation: Create namespaces for objects in your deployment.)
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm INFO: 
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm ERROR: kube-linter run failed with exit code 1
2022-04-14 06:50:16,705 app_build_suite.build_steps.helm ERROR: Error: found 7 lint errors
```

So the `INFO` lines are actually errors?

**Comment by anvddriesch** [comment]
Yeah the tests are failing due to the linter from what I get out of the logs.

**Comment by marians** [comment]
Thanks for taking care

**Review by anvddriesch — APPROVED** [review]

**Review by marians — APPROVED** [review]

**Pull request merged**
