### PR TITLE
update Dex to v2.33.0

### PR DESCRIPTION
**Pull request by gusevda**
Dex was updated to v2.33.0

## Checklist

- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by anvddriesch — APPROVED** [review]
Looks good!
Failing tests are a general problem in this repo at the moment. We should look at it when we have time.

**Comment by anvddriesch** [comment]
However, before releasing it would be good to test it in a test installation. If you want to do that together I think I have time only next week.

**Comment by gusevda** [comment]
Thanks for the review. I would like to test it together. Next week works for me.

**Comment by marians** [comment]
For testing: please make sure to test token refreshing. So start with fresh kubeconfig, then login, then after more than 30 minutes use the context again.

**Pull request merged**
